name: build
run-name: build
on:
  push:
    tags:        
      - '**'
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install typescript
      - run: npm install -g vite
      - run: npm install -g web-ext
      - run: npm install -g ts-node
      - run: vite build
      - run: tsc
      - run: tsc ./src/scripts/your-css.ts --outdir ./dist/scripts/ --skiplibcheck true
      - run: web-ext build --source-dir ./dist/ --overwrite-dest --filename your-css.zip
      - uses: actions/upload-artifact@v4
        with:
          name: your-css
          path: ./web-ext-artifacts/your-css.zip
      - uses: softprops/action-gh-release@v2
        with:
          files: ./web-ext-artifacts/your-css.zip
          tag_name: ${{ github.ref_name }}
