name: build
run-name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install typescript
      - run: npm install -g vite
      - run: npm install -g web-ext
      - run: vite build
      - run: tsc
      - run: web-ext build --source-dir ./dist/ --overwrite-dest --filename pack.zip
      - uses: actions/upload-artifact@v4
        with:
          name: your-css
          path: ./web-ext-artifacts/pack.zip
